### ISSUE TITLE
Async vs normal function 

### ISSUE THREAD

**Issue by modanova** [fac26/week6-fullstack-king#39]
Unnecessary async and await syntax
[code here](https://github.com/fac26/week6-fullstack-king/blob/96517607a088bf1f03037324aa770b406b56cb31/pages/index.js#L20-L21)

I think it will still work if you only had
``` javascript
export function getStaticProps() {
const allFruits = getAllFruits();
```

**Comment by nataliarusu** [comment]
Thanks! This is true. We just wanted to simulate the real world getting data from database - we are aware it will work without async await. Thank you very much for reviewing our code!
