### ISSUE TITLE
Wow 🥳 

### ISSUE THREAD

**Issue by konstantinakatmada** [fac26/week6-fullstack-king#42]
Congrats, team king! 
Impressive how you managed to pass all of the acceptance criteria and some stretch goals in such a short timeframe. I like your choice of creating a React context object which is using the createContext method in order to add items to the cart of the fruitshop(wrapping the relevant components with the context provider so that the components can access the shared state and methods)

**Comment by rockyrelay** [comment]
Thanks, Konstantina! I think on reflection, we haven't quite met the variant picker as planned - but we're working on it! ☺️
