### ISSUE TITLE
Responsiveness?

### ISSUE THREAD

**Issue by yassienAbdillahi** [fac26/week6-fullstack-king#49]
Currently, on mobiles some of the fruits that are for sale do not display properly i.e.

<img width="754" alt="Screenshot 2023-02-23 at 06 31 01" src="https://user-images.githubusercontent.com/95880683/220835145-64eb09c5-bf21-4005-83fc-e0ba8964b638.png">

You can fix this by using the autofit, minmax thing from the pre-apprenticeship CSS layout workshop. Just replace this line here:

https://github.com/fac26/week6-fullstack-king/blob/96517607a088bf1f03037324aa770b406b56cb31/components/FruitList.module.css#L6

with `grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr));`

**Comment by rockyrelay** [comment]
Thanks Yassien! We're implementing this now.
