### ISSUE TITLE
Underlines for links?

### ISSUE THREAD

**Issue by yassienAbdillahi** [fac26/week6-fullstack-king#51]
It might be a good idea to add underlines for links to the individual product pages (for accessibility reasons). Currently it's not immediately obvious (without hovering) that "See more at Lime" for example is a clickable link.

<img width="859" alt="Screenshot 2023-02-23 at 06 50 51" src="https://user-images.githubusercontent.com/95880683/220838019-1a8df08a-513f-4b1c-bdbc-0980bc99abd8.png">

**Comment by nataliarusu** [comment]
Thank you very much, Yassien. We totally agree with you!
